using collections;

GenericCollection.GenericCollectionMethod();
NonGenericCollection.NonGenericCollectionMethod();
EnumerableQueryableExample.EnumerableQueryableExampleMethod();
LinqCollectionsExample.LinqCollectionsExampleMethod();